# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [ main ]
    paths:
      - 'environments/dev/**'
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: "eu-west-2"  # Set the AWS region as an environment variable

permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.2.0
        with:
          role-to-assume: "arn:aws:iam::017373135945:role/role_dev"
          role-session-name: "GitHub_to_AWS_via_FederatedOIDC"
          aws-region: "${{ env.AWS_REGION }}"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init
        working-directory: environments/dev

      - name: Terraform Validate
        run: terraform validate
        working-directory: environments/dev

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan
        working-directory: environments/dev

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve
        working-directory: environments/dev