# This is a basic workflow to help you get started with Actions
on:
  push:
    branches: [ main ]
    paths:
      - 'environments/prod/**'
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: "eu-west-2"  # Set the AWS region as an environment variable

# Permissions can be added at the job level or workflow level
permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.2.0
        with:
          role-to-assume: "arn:aws:iam::017373135945:role/role_prod"  # AWS role to assume
          role-session-name: "GitHub_to_AWS_via_FederatedOIDC"       # Session name for the role
          aws-region: "${{ env.AWS_REGION }}"                       # Use the AWS region from the environment variable

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity  # Check the identity of the assumed role